import json
from pathlib import Path


METHODS = [
    ("Baseline (Regex)", "baseline"),
    (r"\model{Donut}", "donut"),
    (r"\model{LayoutXLM}", "layoutxlm"),
]
FIELDS = ["store_name", "date", "total", "address", "macro"]


def load_json(path: str):
    return json.loads(Path(path).read_text(encoding="utf-8"))


def percent(value: float) -> str:
    return f"{value * 100:.2f}".replace(".", ",")


def decimal(value: float) -> str:
    return f"{value:.2f}".replace(".", ",")


def metric_rows(metrics, view: str, metric: str) -> str:
    rows = []
    for label, key in METHODS:
        data = metrics[key] if view == "all" else metrics[key]["present_only"]
        values = " & ".join(percent(data[field][metric]) for field in FIELDS)
        rows.append(f"{label} & {values} \\\\")
    return "\n".join(rows)


def generate_results_table(metrics) -> str:
    return rf"""% Generated by scripts/generate_report_artifacts.py.
\begin{{table}}[htbp]
  \centering
  \caption{{Kết quả trên toàn bộ 234 mẫu kiểm thử. Macro là trung bình không trọng số của bốn trường.}}
  \label{{tab:all-results}}
  \small
  \begin{{tabularx}}{{\textwidth}}{{l C{{1.55cm}} C{{1.55cm}} C{{1.55cm}} C{{1.55cm}} C{{1.7cm}}}}
    \toprule
    \textbf{{Phương pháp}} & \textbf{{Tên CH}} & \textbf{{Ngày}} & \textbf{{Tổng}} & \textbf{{Địa chỉ}} & \textbf{{Macro}} \\
    \midrule
    \multicolumn{{6}}{{l}}{{\textbf{{Exact Match (EM \%) $\uparrow$}}}} \\
{metric_rows(metrics, "all", "EM")}
    \midrule
    \multicolumn{{6}}{{l}}{{\textbf{{Normalized Edit Similarity (NES \%) $\uparrow$}}}} \\
{metric_rows(metrics, "all", "NES")}
    \midrule
    \multicolumn{{6}}{{l}}{{\textbf{{Character Error Rate (CER \%) $\downarrow$}}}} \\
{metric_rows(metrics, "all", "CER")}
    \bottomrule
  \end{{tabularx}}
\end{{table}}

\begin{{table}}[htbp]
  \centering
  \caption{{Kết quả chỉ trên các mẫu có nhãn ground-truth khác rỗng của từng trường (present-only).}}
  \label{{tab:present-results}}
  \small
  \begin{{tabularx}}{{\textwidth}}{{l C{{1.55cm}} C{{1.55cm}} C{{1.55cm}} C{{1.55cm}} C{{1.7cm}}}}
    \toprule
    \textbf{{Phương pháp}} & \textbf{{Tên CH}} & \textbf{{Ngày}} & \textbf{{Tổng}} & \textbf{{Địa chỉ}} & \textbf{{Macro}} \\
    \midrule
    \multicolumn{{6}}{{l}}{{\textbf{{Exact Match (EM \%) $\uparrow$}}}} \\
{metric_rows(metrics, "present", "EM")}
    \midrule
    \multicolumn{{6}}{{l}}{{\textbf{{Normalized Edit Similarity (NES \%) $\uparrow$}}}} \\
{metric_rows(metrics, "present", "NES")}
    \midrule
    \multicolumn{{6}}{{l}}{{\textbf{{Character Error Rate (CER \%) $\downarrow$}}}} \\
{metric_rows(metrics, "present", "CER")}
    \bottomrule
  \end{{tabularx}}
\end{{table}}
"""


def generate_latency_table(latency) -> str:
    values = {
        "baseline": latency["baseline"]["e2e"]["mean_ms"],
        "layoutxlm": latency["layoutxlm"]["e2e"]["mean_ms"],
        "donut": latency["donut"]["e2e"]["mean_ms"],
    }
    return rf"""% Generated by scripts/generate_report_artifacts.py.
\begin{{table}}[htbp]
  \centering
  \caption{{Thời gian trung bình của thành phần được ghi nhận trong prediction artifact.}}
  \label{{tab:latency-comparison}}
  \begin{{tabular}}{{llr}}
    \toprule
    \textbf{{Phương pháp}} & \textbf{{Phạm vi phép đo}} & \textbf{{Trung bình (ms/ảnh)}} \\
    \midrule
    Baseline (Regex) & Hậu xử lý từ OCR cache & {decimal(values["baseline"])} \\
    \model{{LayoutXLM}} & Suy luận mô hình từ OCR cache & {decimal(values["layoutxlm"])} \\
    \model{{Donut}} & Suy luận và hậu xử lý trực tiếp từ ảnh & {decimal(values["donut"])} \\
    \bottomrule
  \end{{tabular}}
\end{{table}}
"""


def main():
    metrics = {
        key: load_json(f"outputs/metrics/{key}_metrics.json")
        for _, key in METHODS
    }
    latency = load_json("outputs/metrics/latency_by_method.json")
    output_dir = Path("report/generated")
    output_dir.mkdir(parents=True, exist_ok=True)
    (output_dir / "results_tables.tex").write_text(
        generate_results_table(metrics),
        encoding="utf-8",
    )
    (output_dir / "latency_table.tex").write_text(
        generate_latency_table(latency),
        encoding="utf-8",
    )
    print(f"Generated report artifacts in {output_dir}")


if __name__ == "__main__":
    main()
